import ThemeProvider from "@/provider/ThemeProvider";
import "./globals.css";
import { Tajwal, Cairo } from "@/lib/fonts";
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" suppressHydrationWarning>
      <body  className={`${Tajwal.variable} ${Cairo.variable}`}>
        
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >

        {children}
        <Toaster richColors position="bottom-right" closeButton/>
        </ThemeProvider>
        </body>
    </html>
  );
}
